name: win64

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build
        run: zig build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FrostbiteGen-win64
          path: zig-out/bin/
